facebook_mvc/Models/friend.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facebook_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public int f_id { get; set; }
        public int user_id { get; set; }
        public int friend_id { get; set; }
    
        public virtual user_profile user_profile { get; set; }
        public virtual user_profile user_profile1 { get; set; }
    }
}

facebook_mvc/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using facebook_mvc.Models;
using facebook_mvc.View_Models;

namespace facebook_mvc.Controllers
{
    public class FriendsController : Controller
    {
        db_facebookEntities db = new db_facebookEntities();

        // GET: Friends
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult profile()
        {
            var user_id = Convert.ToInt32(Session["id"]);

            return View(db.friends.Where(m => m.friend_id == user_id).ToList());
        }

        public ActionResult friend_requst()
        {
            var user_id = Convert.ToInt32(Session["id"]);
            return View(db.friend_requests.Where(m => m.user_id == user_id  ).ToList());
        }

        public ActionResult myFriend(int friend_id)
        {
           // string state = "puplic";
            int x = Convert.ToInt32(Session["id"]);

            var userinfo = db.user_profile.Find(friend_id );
            //var p_posts = db.posts.Where(p => p.post_state.Contains(state));
            addpost user = new addpost
            {
                user = userinfo
            };

            return View(user);
        }

        public ActionResult accept(int friend_id)
        {
            int user_id = Convert.ToInt32(Session["id"]);
            int f_id = Convert.ToInt32(friend_id);

            friend friend_0 = new friend();

            friend_0.user_id = user_id;
            friend_0.user_profile = db.user_profile.Find(user_id);

            friend_0.friend_id = f_id;
            friend_0.user_profile1 = db.user_profile.Find(f_id);

            db.friends.Add(friend_0);
            db.SaveChanges();

            friend friend_1 = new friend();


            friend_1.friend_id = user_id;
            friend_1.user_profile1 = db.user_profile.Find(user_id);

            friend_1.user_id = f_id;
            friend_1.user_profile = db.user_profile.Find(f_id);

            db.friends.Add(friend_1);
            db.SaveChanges();

            db.friend_requests.RemoveRange(db.friend_requests.Where(m => m.user_id == user_id && m.request_id == friend_id).ToList());
            db.SaveChanges();


            return RedirectToAction("friend_requst");

        }

        public ActionResult reject(int friend_id)
        {
            int user_id = Convert.ToInt32(Session["id"]);
            int f_id = Convert.ToInt32(friend_id);

            db.friend_requests.RemoveRange(
                db.friend_requests.Where(
                    r => r.user_id == f_id && r.user_id == f_id).ToList());
            db.SaveChanges();


            return RedirectToAction("Index","Profile");
        }
    }
}

facebook_mvc/Controllers/ProfileController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using facebook_mvc.Models;
using facebook_mvc.View_Models;


namespace facebook_mvc.Controllers
{
    public class ProfileController : Controller
    {
        db_facebookEntities db = new db_facebookEntities();
        // GET: Profile
        public ActionResult Index()
        {
            
            int x = Convert.ToInt32(Session["id"]);
            var userinfo = db.user_profile.Find(x);
            addpost user = new addpost
            {
                user = userinfo

            };

            return View(user);
        }
        [HttpGet]
        public ActionResult addpost()
         {
            return RedirectToAction("Index", "Profile");
        }

         [HttpPost]
         public ActionResult addpost(string post_description)
         {
            post post = new post();
            string state = "puplic";
            int likes = 0;
            int user_id = Convert.ToInt32(Session["id"]);
            post.likesNumber = likes;
            post.post_state = state;
            post.user_id = user_id;
            post.post_description = post_description;
            db.posts.Add(post);
            db.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }


        public ActionResult addcomment()
        {
            return View();

        }

        [HttpPost]
        public ActionResult addcomment(comment comment)
        {
            int x = Convert.ToInt32(Session["id"]);

            //comment comment = new comment();

            
            comment.user_id = x;

            db.comments.Add(comment);
            db.SaveChanges();

            return RedirectToAction("Index", "Profile");

        }

        public ActionResult single_post(int post_id)
        {

            var post = db.posts.Include(e=> e.comments).Single(e => e.post_id == post_id);

            
            return View(post);
            

        }


        [HttpGet]
        public ActionResult editpost()
        {
            return RedirectToAction("Index", "Profile");
        }

        [HttpPost]
        public ActionResult editpost(post post)
        {
            int x = Convert.ToInt32(Session["id"]);
            post.user_id = x;
           
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;

                db.Entry(post).Property("post_description").IsModified = false;
                db.Entry(post).Property("likesNumber").IsModified = false;

                db.SaveChanges();

                return RedirectToAction("Index","Profile");
            }


            return RedirectToAction("Index", "Profile");
        }

        public ActionResult edit_post_page (int post_id)
        {
            var post = db.posts.Include(e => e.comments).Single(e => e.post_id == post_id);

            return View(post);
        }



    }
}

facebook_mvc/Controllers/ReactController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using facebook_mvc.Models;

namespace facebook_mvc.Controllers
{
    public class ReactController : Controller
    {
        // GET: React
        db_facebookEntities db = new db_facebookEntities();
        public ActionResult Like(int post_id)
        {

            var post = db.posts.Find(post_id);
            post.likesNumber++;

            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Profile");

            }
            
            return RedirectToAction("Index", "Profile");
        }


        public ActionResult Dislike(int post_id)
        {

            var post = db.posts.Find(post_id);
            post.likesNumber--;

            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Profile");

            }

            return RedirectToAction("Index", "Profile");
        }
    }
}

facebook_mvc/Views/Friends/friend_requst.cshtml
@model IList<facebook_mvc.Models.friend_requests>

@{
    Layout = "~/Views/Shared/_Navbar.cshtml";
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="images/fb-icon-sm.png">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/bootstrap.css">
    <s>
        <link rel="stylesheet" href="~/css/bootstrap.min.css">
    </s>
    <link rel="icon" href="~/images/fb-icon-sm.png">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Facebook</title>
</head>
<body>
    <!-- the main body container of both Request&Suggestion used bootstrap so some classs make no sence
        what we need is the container with the class friend-request & friend-suggestion -->
    <div class="container card my-5">

        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <!--Friend Request tab  -->
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="requests-tab" data-bs-toggle="tab" data-bs-target="#requests"
                        type="button" role="tab" aria-controls="home" aria-selected="true">
                    Friends Requests
                </button>
            </li>

        </ul>
        <!-- tabs content -->

        <div class="tab-content" id="myTabContent">
            <!-- friend request container start  -->
            @{ foreach (var item in Model)
                {
                    <div class="tab-pane fade show active" id="requests" role="tabpanel" aria-labelledby="requests-tab">
                        <!-- friend request -->
                        <div id="friend-request" class="friend-request  py-3">
                            <a id="friend-request-profile" href="view-friend-request-profile.html" class="account-data flex">
                                <!-- account img -->

                                <img id="account-img " class="account-img rounded-circle" src="@Url.Content(item.user_profile.profile_img)" alt="" class="img">
                                <!-- account name -->
                                <h2 id="account-name" class="account-name">@item.user_profile.Fname @item.user_profile.Lname</h2>
                            </a>
                            <!-- btns -->
                            <div class="add-delete">
                                <!--Accept btn  -->
                                <a href="@Url.Action("accept", "Friends", new { friend_id = item.user_profile.user_id })"  id="accept-add" class="btn btn-outline-primary">Accept</a>
                                <!-- Delete -->
                                <a href="@Url.Action("reject", "Friends", new { friend_id = item.user_profile1.user_id })" id="delete-add" class="btn btn-outline-danger">Delete</a>
                            </div>


                        </div>
                    </div>}}

        </div>

    </div>

</body>

</html>

facebook_mvc/Views/Friends/myFriend.cshtml
@model facebook_mvc.View_Models.addpost

@{
    Layout = "~/Views/Shared/_Navbar.cshtml";
}




<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/images/fb-icon-sm.png">

    <link rel="stylesheet" href="~/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/style.css">
    <title>Facebook</title>
</head>

<body>

    <!-- ----------------------profile info section---------------- -->
    <div class="card">
        <div class="container">
            <div class="profile-info">
                <div class="container  flex ">
                    <div class="flex">
                        <!-- profile img -->
                        <img id="account-img" src="@Url.Content(Model.user.profile_img)" alt="" class="img">
                        <!-- user info -->
                        <div class="user-info">
                            <h2 id="account-name" class="user-name">@Model.user.Fname @Model.user.Lname</h2>
                            
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- ----------------------news feed section---------------- -->

    <div class="container posts-container">
        @{foreach (var item in Model.user.posts)
            {
                if (item.post_state == "puplic")
                {
                <!-- post card -->
        <div id="account-post" class="post card my-3">
            <div id="account-info" class="user-info flex">
                <img id="account-img" src="@Url.Content(Model.user.profile_img)" alt="" class="img">
                <h5 class="account-name">@Model.user.Fname @Model.user.Lname</h5>
            </div>
            <hr>
            <!-- post text -->
            <p id="post-text" style="font-size: 20px;" class="my-2">
                @item.post_description
            </p>
            <!-- post main img -->
            @*<img id="post-img" class="" src="~/images/post-img-demo.jpg" alt="">*@
            <!-- likes count -->
            <p class="likes-count my-2"><span id="likes-count">@item.likesNumber</span> like this post</p>
            <hr>
            <!-- like and comment btns -->
            <div class="post-interact flex">
                <!-- like btn -->
                <div id="like-btn" class="like">
                    <a href="@Url.Action("Like", "React", new { post_id = item.post_id })" class="btn btn-primary">
                        <i class="fa fa-thumbs-up" style="font-size:30px"></i>
                        like
                    </a>
                </div>
                <!-- comment btn -->
                <div id="dislike-btn" class="like">
                    <a href="@Url.Action("Dislike", "React", new { post_id = item.post_id })" class="btn btn-primary">

                        <i class="fa fa-thumbs-down"
                           style="font-size:29px"></i>
                        Dislike
                    </a>
                </div>
            </div>

            <hr>
            <a href="@Url.Action("single_post", "Profile", new { post_id = item.post_id })" class="btn btn-primary">
                Add Comment
            </a>
            <br>
            <br>
            @foreach (var i in item.comments)

            {<div id="view-comments" class="view-comments">
                 <div class="flex comment">
                     @*<img id="account-img"class="rounded-circle" src="@Url.Content(item.user_profile.profile_img)" alt="">*@
                                          <div class="comment-body">

                         <p id="comment-text">
                             @i.comment_description
                         </p>
                     </div>
                 </div>
                </div>
            }


        </div>}
                }
            }
        </div>

    <!-- Button trigger modal -->
    <!-- Modal -->

    <button class="btn btn-primary" onclick="topFunction()" id="topBtn" title="Go to top">
        <i class='fas fa-angle-up'
           style='font-size:24px'></i>
    </button>

    <script src="js/bootstrap.bundle.js"></script>

    <script src=" js/main.js"></script>
</body>

</html>

facebook_mvc/Views/Friends/profile.cshtml
@model IList<facebook_mvc.Models.friend>

@{
    Layout = "~/Views/Shared/_Navbar.cshtml";
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="images/fb-icon-sm.png">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/bootstrap.css">
    <s>
        <link rel="stylesheet" href="~/css/bootstrap.min.css">
    </s>
    <link rel="icon" href="~/images/fb-icon-sm.png">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Facebook</title>
</head>
<body>
    <!-- the main body container of both Request&Suggestion used bootstrap so some classs make no sence
        what we need is the container with the class friend-request & friend-suggestion -->
    <div class="container card my-5">

        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <!--Friend Request tab  -->
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="requests-tab" data-bs-toggle="tab" data-bs-target="#requests"
                        type="button" role="tab" aria-controls="home" aria-selected="true">
                    Friends
                </button>
            </li>
            
        </ul>
        <!-- tabs content -->

        <div class="tab-content" id="myTabContent">
            <!-- friend request container start  -->
            @{ foreach (var item in Model)
                {
                    <div class="tab-pane fade show active" id="requests" role="tabpanel" aria-labelledby="requests-tab">
                        <!-- friend request -->
                        <div id="friend-request" class="friend-request  py-3">
                            <a id="friend-request-profile" href="@Url.Action("myFriend", "Friends", new { friend_id = item.user_profile.user_id })" class="account-data flex">
                                <!-- account img -->
                                
                                <img id="account-img " class="account-img rounded-circle" src="@Url.Content(item.user_profile1.profile_img)" alt="" class="img">
                                <!-- account name -->
                                <h2 id="account-name" class="account-name">@item.user_profile1.Fname @item.user_profile1.Lname</h2>
                            </a>
                            <!-- sdd friend btn -->
                            <div class="view-friend">
                                <a href="@Url.Action("myFriend", "Friends", new { friend_id = item.user_profile1.user_id })" class="btn btn-outline-primary">View Profile</a>
                            </div>
                            
                        </div>
                    </div>}}
            
        </div>

    </div>

</body>

</html>